version: "3.7"
services:
  work:
    build:
      context: ./docker/work
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./workspace:/root/workspace
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./workspace/app:/root/workspace/app
